language: c
compiler: gcc
dist: bionic
before_install:
  - sudo apt-get install git lcov uuid-runtime python3-dev autoconf-archive
  - git clone https://github.com/jonasblixt/bpak --depth 1 --branch v0.4.0
script:
    - cd bpak && autoreconf -fi && ./configure && make && sudo make install && cd .. && sudo ldconfig
    - autoreconf -fi && ./configure KEYSTORE_FILE=pki/internal_keystore.bpak --enable-code-coverage && make check
    - cat test/test-suite.log
jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - bash <(curl -s https://codecov.io/bash)
